### PR TITLE
Relax constraint a bit

### PR DESCRIPTION
**Pull request by leofang**
Part of #7.

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by leofang** [comment]
xref: https://github.com/conda-forge/ucx-split-feedstock/pull/123 which fixed the same problem

**Comment by jakirkham** [comment]
Looks good. Thanks Leo! 🙏

**Comment by leofang** [comment]
Confirm fixed:
```
  Prefix: /home/leof/miniforge3/envs/bbbbbb

  Updating specs:

   - nccl
   - cuda-version=10.2


  Package           Version  Build        Channel                    Size
───────────────────────────────────────────────────────────────────────────
  Install:
───────────────────────────────────────────────────────────────────────────

  + _libgcc_mutex       0.1  conda_forge  conda-forge/linux-64     Cached
  + _openmp_mutex       4.5  2_gnu        conda-forge/linux-64     Cached
  + cuda-version       10.2  h4767cc1_2   conda-forge/noarch         21kB
  + cudatoolkit     10.2.89  h713d32c_11  conda-forge/linux-64      333MB
  + libgcc-ng        12.2.0  h65d4601_19  conda-forge/linux-64     Cached
  + libgomp          12.2.0  h65d4601_19  conda-forge/linux-64     Cached
  + libstdcxx-ng     12.2.0  h46fd767_19  conda-forge/linux-64     Cached
  + nccl           2.15.5.1  h1a5f58c_0   conda-forge/linux-64       62MB

  Summary:

  Install: 8 packages

  Total download: 396MB

───────────────────────────────────────────────────────────────────────────


Confirm changes: [Y/n] n
Aborted.
```

**Comment by leofang** [comment]
(Same with `$ mamba install nccl "cuda-version=10.2.*"`)

**Comment by jakirkham** [comment]
Thanks Leo! 🙏

**Pull request merged**
